# Generated by Django 3.1.14 on 2023-04-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('currency_pair', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
