# Generated by Django 3.1.14 on 2023-04-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('commodity_name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('change_price', models.FloatField()),
                ('change_rate', models.FloatField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('index_name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('change_price', models.FloatField()),
                ('change_rate', models.FloatField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
